# ================================================
# FoliaPhantom Configuration
#
# auto-scan-plugins:
#   enabled: true
#     trueに設定すると、'plugins'フォルダ内のすべてのJARが自動的にスキャンされ、
#     Folia非対応のプラグインに対して互換性パッチが適用されます。
#
#   excluded-plugins:
#     - "SomePlugin"
#     - "AnotherPlugin"
#     パッチを適用したくないプラグインのリスト。
#     プラグイン名（plugin.yml内の'name'）で指定してください。
# ================================================
auto-scan-plugins:
  enabled: true
  excluded-plugins:
    - "FoliaPhantom" # 自分自身は除外する
    - "ExamplePlugin"
