name: Auto Release and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # release作成に必要
      packages: write       # GitHub Packagesへのpublishに必要

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file FoliaPhantom/pom.xml

      - name: Create Release Tag
        id: create_tag
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file FoliaPhantom/pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -DskipTests deploy -s $GITHUB_WORKSPACE/settings.xml --file FoliaPhantom/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
