# ================================================
# ラップ対象プラグインを設定するファイル
# このファイルを編集して、任意の外部プラグインを追加してください。
#
# fields:
#   name:              ラップ対象プラグイン名（ログ出力用の識別子）
#   original-jar-path: ラップ対象プラグイン本体 JAR のパス（このプラグインの data フォルダを基準に解釈）
#   patched-jar-path:  Folia 対応したあとの JAR を出力するパス（data フォルダを基準）
#   folia-enabled:     Folia 対応のために plugin.yml を書き換えるかどうか (true/false)
# ================================================
wrapped-plugins:

  - name: WorldEdit
    original-jar-path: "lib/worldedit/WorldEdit.jar"
    patched-jar-path:  "lib/worldedit/WorldEdit-Folia.jar"
    folia-enabled:     true

  # もし他の外部プラグインを追加したい場合は、以下のようにエントリを増やしてください:
  # - name: AnotherPlugin
  #   original-jar-path: "lib/external/AnotherPlugin.jar"
  #   patched-jar-path:  "lib/external/AnotherPlugin-Folia.jar"
  #   folia-enabled:     false
